// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msoop.Infrastructure.Data;

namespace Msoop.Infrastructure.Migrations
{
    [DbContext(typeof(MsoopContext))]
    partial class MsoopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Msoop.Core.Models.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOver18")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSpoilers")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowStickied")
                        .HasColumnType("bit");

                    b.Property<int>("PostAgeLimitInDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.HasKey("Id");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Msoop.Core.Models.Subreddit", b =>
                {
                    b.Property<Guid>("SheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxPostCount")
                        .HasColumnType("int");

                    b.Property<int>("PostOrdering")
                        .HasColumnType("int");

                    b.HasKey("SheetId", "Name");

                    b.ToTable("Subreddits");
                });

            modelBuilder.Entity("Msoop.Core.Models.Subreddit", b =>
                {
                    b.HasOne("Msoop.Core.Models.Sheet", "Sheet")
                        .WithMany("Subreddits")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("Msoop.Core.Models.Sheet", b =>
                {
                    b.Navigation("Subreddits");
                });
#pragma warning restore 612, 618
        }
    }
}
